LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := spriterGM
LOCAL_CFLAGS := -include "src/android_fopen.h"
LOCAL_MODULE_FILENAME := libspriterGM
LOCAL_LDLIBS := -landroid
LOCAL_LDLIBS += -llog
LOCAL_SRC_FILES := \
nlohmann-json/json.hpp \
tinyxml2/tinyxml2.cpp \
tinyxml2/tinyxml2.h \
pugixml/pugiconfig.hpp\
pugixml/pugixml.cpp \
pugixml/pugixml.hpp \
spriterengine/timeline/tagtimelineinstance.cpp \
spriterengine/timeline/variabletimelineinstance.cpp \
spriterengine/timeline/timelineinstance.cpp \
spriterengine/timeline/timelinekey.cpp \
spriterengine/timeline/triggertimelineinstance.cpp \
spriterengine/timeline/soundtimelineinstance.cpp \
spriterengine/timeline/proxytimelinekey.cpp \
spriterengine/timeline/timeline.cpp \
spriterengine/global/settings.cpp \
spriterengine/override/imagefile.cpp \
spriterengine/override/atlasfile.cpp \
spriterengine/override/soundfile.cpp \
spriterengine/override/spriterfiledocumentwrapper.cpp \
spriterengine/override/objectfactory.cpp \
spriterengine/override/spriterfileattributewrapper.cpp \
spriterengine/override/filefactory.cpp \
spriterengine/override/soundobjectinforeference.cpp \
spriterengine/override/spriterfileelementwrapper.cpp \
spriterengine/objectref/spriteref.cpp \
spriterengine/objectref/boneref.cpp \
spriterengine/objectref/transformprocessor.cpp \
spriterengine/objectref/entityref.cpp \
spriterengine/objectref/spriterefinstance.cpp \
spriterengine/objectref/entityrefinstance.cpp \
spriterengine/objectref/objectrefinstance.cpp \
spriterengine/objectref/objectref.cpp \
spriterengine/objectref/bonerefinstance.cpp \
spriterengine/variable/variable.cpp \
spriterengine/variable/variablecontainer.cpp \
spriterengine/variable/variableinstancenameandidmap.cpp \
spriterengine/loading/loader.cpp \
spriterengine/loading/loadinghelpers.cpp \
spriterengine/loading/spriterdocumentloader.cpp \
spriterengine/objectinfo/tagobjectinfo.cpp \
spriterengine/objectinfo/soundobjectinfo.cpp \
spriterengine/objectinfo/spriteobjectinfo.cpp \
spriterengine/objectinfo/intvariableinfo.cpp \
spriterengine/objectinfo/taglist.cpp \
spriterengine/objectinfo/stringvariableinforeference.cpp \
spriterengine/objectinfo/entityobjectinfo.cpp \
spriterengine/objectinfo/eventobjectinfo.cpp \
spriterengine/objectinfo/angleinfo.cpp \
spriterengine/objectinfo/pointinstanceinfo.cpp \
spriterengine/objectinfo/boxinstanceinfo.cpp \
spriterengine/objectinfo/boneinstanceinfo.cpp \
spriterengine/objectinfo/universalobjectinterface.cpp \
spriterengine/objectinfo/realvariableinfo.cpp \
spriterengine/objectinfo/triggerobjectinfo.cpp \
spriterengine/objectinfo/pointobjectinfo.cpp \
spriterengine/objectinfo/boneobjectinfo.cpp \
spriterengine/objectinfo/tagobjectinforeference.cpp \
spriterengine/objectinfo/stringvariableinfo.cpp \
spriterengine/objectinfo/boxobjectinfo.cpp \
spriterengine/charactermap/charactermap.cpp \
spriterengine/charactermap/charactermapinstruction.cpp \
spriterengine/model/spritermodel.cpp \
spriterengine/file/file.cpp \
spriterengine/file/filereference.cpp \
spriterengine/entity/object.cpp \
spriterengine/entity/entity.cpp \
spriterengine/entity/entityinstance.cpp \
spriterengine/entity/entityinstancedata.cpp \
spriterengine/animation/mainlinekey.cpp \
spriterengine/animation/animationinstance.cpp \
spriterengine/animation/mainlinekeyinstance.cpp \
spriterengine/animation/animation.cpp \
spriterengine/timeinfo/cubiceasingcurve.cpp \
spriterengine/timeinfo/easingcurveinterface.cpp \
spriterengine/timeinfo/timeinfo.cpp \
spriterengine/timeinfo/instanteasingcurve.cpp \
spriterengine/timeinfo/quarticeasingcurve.cpp \
spriterengine/timeinfo/quadraticeasingcurve.cpp \
spriterengine/timeinfo/beziereasingcurve.cpp \
spriterengine/timeinfo/lineareasingcurve.cpp \
spriterengine/timeinfo/quinticeasingcurve.cpp \
src/gmatlasfile.cpp \
src/gmatlasfile.h \
src/gmboneinstanceinfo.cpp \
src/gmboneinstanceinfo.h \
src/gmboxinstanceinfo.cpp \
src/gmboxinstanceinfo.h \
src/gmfilefactory.cpp \
src/gmfilefactory.h \
src/gmimagefile.cpp \
src/gmimagefile.h \
src/gmobjectfactory.cpp \
src/gmobjectfactory.h \
src/gmpointinstanceinfo.cpp \
src/gmpointinstanceinfo.h \
src/gmsoundfile.cpp \
src/gmsoundfile.h \
src/gmsoundobjectinforeference.cpp \
src/gmsoundobjectinforeference.h \
src/gmtriggerobjectinfo.cpp \
src/gmtriggerobjectinfo.h \
src/jsonspriterfileattributewrapper.cpp \
src/jsonspriterfileattributewrapper.h \
src/jsonspriterfiledocumentwrapper.cpp \
src/jsonspriterfiledocumentwrapper.h \
src/jsonspriterfileelementwrapper.cpp \
src/jsonspriterfileelementwrapper.h \
src/mainjni.cpp \
src/mainjni.h \
src/maindll.cpp \
src/maindll.h \
src/pugixmlspriterfileattributewrapper.cpp \
src/pugixmlspriterfileattributewrapper.h \
src/pugixmlspriterfiledocumentwrapper.cpp \
src/pugixmlspriterfiledocumentwrapper.h \
src/pugixmlspriterfileelementwrapper.cpp \
src/pugixmlspriterfileelementwrapper.h \
src/spriterGM.cpp \
src/spriterGM.h \
src/tinyxmlspriterfileattributewrapper.cpp \
src/tinyxmlspriterfileattributewrapper.h \
src/tinyxmlspriterfiledocumentwrapper.cpp \
src/tinyxmlspriterfiledocumentwrapper.h \
src/tinyxmlspriterfileelementwrapper.cpp \
src/tinyxmlspriterfileelementwrapper.h \
src/android_fopen.c \

include $(BUILD_SHARED_LIBRARY)
