/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libspritergm_spriterGMNative */

#ifndef _Included_com_libspritergm_spriterGMNative
#define _Included_com_libspritergm_spriterGMNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libspritergm_spriterGMNative
 * Method:    spriter_LoadModel
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_libspritergm_spriterGMNative_spriter_1LoadModel
  (JNIEnv *env, jclass object, jstring filePath);

#ifdef __cplusplus
}
#endif
#endif
